using System.Collections.Generic;

namespace AIBridgeCLI.Commands
{
    public class CodeIndexCommandBuilder : BaseCommandBuilder
    {
        public override string Type => "code_index";
        public override string Description => "Read-only Unity snapshot C# declaration name index";

        public override string[] Actions => new[]
        {
            "status",
            "doctor",
            "build_snapshot",
            "warmup",
            "reset",
            "symbol",
            "definition"
        };

        protected override Dictionary<string, List<ParameterInfo>> ActionParameters => new Dictionary<string, List<ParameterInfo>>
        {
            ["status"] = CommonParameters(),
            ["doctor"] = CommonParameters(),
            ["build_snapshot"] = WithBuildSnapshotParameters(),
            ["warmup"] = WithWarmupParameters(),
            ["reset"] = WithResetParameters(),
            ["symbol"] = WithQuery(new List<ParameterInfo>
            {
                new ParameterInfo("query", "C# declaration name or partial name", true)
            }),
            ["definition"] = WithQuery(new List<ParameterInfo>
            {
                new ParameterInfo("query", "C# declaration name", true)
            })
        };

        private static List<ParameterInfo> CommonParameters()
        {
            return new List<ParameterInfo>
            {
                new ParameterInfo("project-root", "Unity project root. Defaults to current Unity project", false),
                new ParameterInfo("unity-pid", "Unity Editor process id to monitor. Daemon exits when the process is gone", false),
                new ParameterInfo("auto-refresh", "Reload the snapshot workspace automatically when snapshot files change", false, "true"),
                new ParameterInfo("warmup-mode", "Daemon startup warmup mode: names or light", false, "names")
            };
        }

        private static List<ParameterInfo> WithResetParameters()
        {
            var parameters = CommonParameters();
            parameters.Add(new ParameterInfo("include-snapshot", "Delete the Unity compilation snapshot in addition to daemon state", false, "false"));
            return parameters;
        }

        private static List<ParameterInfo> WithWarmupParameters()
        {
            var parameters = CommonParameters();
            parameters.Add(new ParameterInfo("priority", "Daemon process priority: normal or low", false, "normal"));
            return parameters;
        }

        private static List<ParameterInfo> WithBuildSnapshotParameters()
        {
            var parameters = CommonParameters();
            parameters.Add(new ParameterInfo("input", "Compiler input JSON generated by Unity", true));
            parameters.Add(new ParameterInfo("workers", "Snapshot worker count override", false, "auto"));
            parameters.Add(new ParameterInfo("priority", "Snapshot worker process priority: normal or low", false, "normal"));
            return parameters;
        }

        private static List<ParameterInfo> WithQuery(List<ParameterInfo> parameters)
        {
            parameters.AddRange(CommonParameters());
            return parameters;
        }
    }
}
